# name: Build and Deploy application

on:
  push:
    branches: [ main, development, staging ]
  pull_request:
    branches: [ main, development, staging ]

jobs:
   pre-release:
    name: "Pre Release"
    runs-on: ubuntu-latest

    steps:
      
      - name: "Build"
        run: |
          go build
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: github.ref == 'refs/heads/main', 'refs/heads/development'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: Pre-Release
          files: |
            LICENSE.txt
            *.jar
            
    deploy:
    needs: pre-release
     name: "Deploy to Netlify for staging"
     runs-on: ubuntu-latest
     
     if: github.ref == 'refs/heads/staging'
     steps:
       - uses: jsmrcaga/action-netlify-deploy@v1.1.0
         with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.MY_TOKEN_SECRET }}
          NETLIFY_DEPLOY_TO_PROD: true
         run: |
          echo "Deployed @ ${{netlifyURL.secrets}}"



